import playfunction as pf

pf.playNote("G4", "quarter", pieceSpeed=100, function="sine")
pf.playNote("A4", "quarter", pieceSpeed=100, function="sine")
pf.playNote("B4", "quarter", pieceSpeed=100, function="sine")
pf.playNote("C5", "half", pieceSpeed=100, function="sine")
pf.playNote("C5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("D5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("E5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("F5", "half", pieceSpeed=100, function="sine")
pf.playNote("G5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("F5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("E5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("D5", "half", pieceSpeed=100, function="sine")
pf.playNote("C5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("D5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("E5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("F5", "half", pieceSpeed=100, function="sine")
pf.playNote("G5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("F5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("E5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("D5", "half", pieceSpeed=100, function="sine")
pf.playNote("C5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("D5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("E5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("F5", "half", pieceSpeed=100, function="sine")
pf.playNote("G5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("F5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("E5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("D5", "half", pieceSpeed=100, function="sine")
pf.playNote("C5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("D5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("E5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("F5", "half", pieceSpeed=100, function="sine")
pf.playNote("G5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("F5", "quarter", pieceSpeed=100, function="sine")
pf.playNote("E5", "quarter", pieceSpeed=100, function="sine")


if _name_ == '_main_':
    main()




    pf.playNote("C4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("D4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")

    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")

    pf.playNote("E4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("D4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("F4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("E4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("E4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("D4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("D4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("D4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("B3", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("D4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("C4", "half", pieceSpeed=100, function="sine")
    pf.playNote("C4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("G4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("G4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("G4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("G4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("G4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("F4#", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("G4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("G4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("F4#", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("A4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("G4", "eighth", pieceSpeed=100, function="sine")
    pf.playNote("F4", "quarter", pieceSpeed=100, function="sine")
    pf.playNote("F4", "eighth", pieceSpeed=100, function="sine")